version: '3.4'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: azure_p1
      POSTGRES_USER: azure_p1
      POSTGRES_DB: azure_p1
    ports:
      - "54326:5432"
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    ports:
      - "10000:10000"
