spring:
  datasource:
    url: jdbc:postgresql://localhost:54326/azure_p1
    username: azure_p1
    password: azure_p1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

app:
  archivization:
    interval-ms: 60000
    report-age-threshold: PT3H
    container-name: reports-archive
  storage:
    azure-connection-string: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;

